id = "currency-converter"
name = "Currency Converter"
description = "Convert currencies easily"
keywords = ["currency","converter","exchange"]
icon = "assests/icon.svg"
version = "0.0.1"
author = "Stall"
repo = "https://github.com/yourusername/my-extension"
homepage = "https://stallpos.com"
offline_ready = true

